version: '3.8'
services: 
  frontend:
    build: ./frontend
    container_name: express-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb+srv://prasunpersonal:Q660s6tAlJKp3o3A@prasunpersonal.qze2n.mongodb.net/?retryWrites=true&w=majority
    volumes:
      - ./backend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge