apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.io/devprasun/todo-backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-url
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: todo
spec:
  selector:
    app: backend
  ports:
  - port: 4000
    targetPort: 5000
---
